// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxypznfbsnerboaxtslx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4eXB6bmZic25lcmJvYXh0c2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3ODIwOTEsImV4cCI6MjA1NjM1ODA5MX0.Qq1dP98xp0sYheZhB41pRQ2TyrSfsnDAN8yCIDN3Mjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);